### ISSUE TITLE
RSC change from inner to outer merging to get more data

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#181]
In level2/compute_radial_surface_current:

`level2['RadialSurfaceCurrent'] = xr.concat(
        [level1.RadialSurfaceVelocity.sel(Antenna='Fore') - dswasv_f,
         level1.RadialSurfaceVelocity.sel(Antenna='Aft') - dswasv_a],
        'Antenna', join='inner')`

join could certainly be changed to "outer" at this stage. To test how it affects the rest of the chain

**Comment by DavidMcCann-NOC** [comment]
This was likely originally joined by 'outer', however I have found problems with coordinates downstream - e.g., lat/lon coordinates being padded by NaNs after joining. Currently joining by 'inner' solves these issues - however I agree that we should aim to have the full datasets present in the joined version. We will need to solve the creation and assignment of the lat/lon coordinates to the datasets in order to achieve this.

Currently these coords are taken from the LatImage / LonImage arrays, which are specific to a look direction. We will therefore need to join/merge the LatImage / LonImage arrays into one big one to cover the 'outer' joined dataset

**Comment by DavidMcCann-NOC** [comment]
Linked with #185

**Comment by DavidMcCann-NOC** [comment]
Believed to be closed with pull request #192.

Test to see that the RSC data being passed to the L2 processing is indeed 'outer' in size before closing.

**Comment by DavidMcCann-NOC** [comment]
(accidentally closed)

**Comment by DavidMcCann-NOC** [comment]
Closed as of #192 and more recently confirmed with #224
